/*
 * lsm_defines.h
 *
 *  Created on: Sep 21, 2021
 *      Author: Thi Han
 */

#ifndef MAIN_COMPONENTS_LSM6DSOX_LSM_DEFINES_H_
#define MAIN_COMPONENTS_LSM6DSOX_LSM_DEFINES_H_

#define PROPERTY_DISABLE                      (0U)
#define PROPERTY_ENABLE                       (1U)
#define LSM6DSOX_I2C_ADD_L                    0xD5U
#define LSM6DSOX_I2C_ADD_H                    0xD7U
#define LSM6DSOX_ID                           0x6CU
#define LSM6DSOX_FUNC_CFG_ACCESS              0x01U
#define LSM6DSOX_PIN_CTRL                     0x02U
#define LSM6DSOX_S4S_TPH_L                    0x04U
#define LSM6DSOX_S4S_TPH_H                    0x05U
#define LSM6DSOX_S4S_RR                       0x06U
#define LSM6DSOX_FIFO_CTRL1                   0x07U
#define LSM6DSOX_FIFO_CTRL2                   0x08U
#define LSM6DSOX_FIFO_CTRL3                   0x09U
#define LSM6DSOX_FIFO_CTRL4                   0x0AU
#define LSM6DSOX_COUNTER_BDR_REG1             0x0BU
#define LSM6DSOX_COUNTER_BDR_REG2             0x0CU
#define LSM6DSOX_INT1_CTRL                    0x0D
#define LSM6DSOX_INT2_CTRL                    0x0EU
#define LSM6DSOX_WHO_AM_I                     0x0FU
#define LSM6DSOX_CTRL1_XL                     0x10U
#define LSM6DSOX_CTRL2_G                      0x11U
#define LSM6DSOX_CTRL3_C                      0x12U
#define LSM6DSOX_CTRL4_C                      0x13U
#define LSM6DSOX_CTRL5_C                      0x14U
#define LSM6DSOX_CTRL6_C                      0x15U
#define LSM6DSOX_CTRL7_G                      0x16U
#define LSM6DSOX_CTRL8_XL                     0x17U
#define LSM6DSOX_CTRL9_XL                     0x18U
#define LSM6DSOX_CTRL10_C                     0x19U
#define LSM6DSOX_ALL_INT_SRC                  0x1AU
#define LSM6DSOX_WAKE_UP_SRC                  0x1BU
#define LSM6DSOX_TAP_SRC                      0x1CU
#define LSM6DSOX_D6D_SRC                      0x1DU
#define LSM6DSOX_STATUS_REG                   0x1EU
#define LSM6DSOX_OUT_TEMP_L                   0x20U
#define LSM6DSOX_OUT_TEMP_H                   0x21U
#define LSM6DSOX_OUTX_L_G                     0x22U
#define LSM6DSOX_OUTX_H_G                     0x23U
#define LSM6DSOX_OUTY_L_G                     0x24U
#define LSM6DSOX_OUTY_H_G                     0x25U
#define LSM6DSOX_OUTZ_L_G                     0x26U
#define LSM6DSOX_OUTZ_H_G                     0x27U
#define LSM6DSOX_OUTX_L_A                     0x28U
#define LSM6DSOX_OUTX_H_A                     0x29U
#define LSM6DSOX_OUTY_L_A                     0x2AU
#define LSM6DSOX_OUTY_H_A                     0x2BU
#define LSM6DSOX_OUTZ_L_A                     0x2CU
#define LSM6DSOX_OUTZ_H_A                     0x2DU
#define LSM6DSOX_EMB_FUNC_STATUS_MAINPAGE     0x35U
#define LSM6DSOX_FSM_STATUS_A_MAINPAGE        0x36U
#define LSM6DSOX_FSM_STATUS_B_MAINPAGE        0x37U
#define LSM6DSOX_MLC_STATUS_MAINPAGE          0x38U
#define LSM6DSOX_STATUS_MASTER_MAINPAGE       0x39U
#define LSM6DSOX_FIFO_STATUS1                 0x3AU
#define LSM6DSOX_FIFO_STATUS2                 0x3B
#define LSM6DSOX_TIMESTAMP0                   0x40U
#define LSM6DSOX_TIMESTAMP1                   0x41U
#define LSM6DSOX_TIMESTAMP2                   0x42U
#define LSM6DSOX_TIMESTAMP3                   0x43U
#define LSM6DSOX_UI_STATUS_REG_OIS            0x49U
#define LSM6DSOX_UI_OUTX_L_G_OIS              0x4AU
#define LSM6DSOX_UI_OUTX_H_G_OIS              0x4BU
#define LSM6DSOX_UI_OUTY_L_G_OIS              0x4CU
#define LSM6DSOX_UI_OUTY_H_G_OIS              0x4DU
#define LSM6DSOX_UI_OUTZ_L_G_OIS              0x4EU
#define LSM6DSOX_UI_OUTZ_H_G_OIS              0x4FU
#define LSM6DSOX_UI_OUTX_L_A_OIS              0x50U
#define LSM6DSOX_UI_OUTX_H_A_OIS              0x51U
#define LSM6DSOX_UI_OUTY_L_A_OIS              0x52U
#define LSM6DSOX_UI_OUTY_H_A_OIS              0x53U
#define LSM6DSOX_UI_OUTZ_L_A_OIS              0x54U
#define LSM6DSOX_UI_OUTZ_H_A_OIS              0x55U
#define LSM6DSOX_TAP_CFG0                     0x56U
#define LSM6DSOX_TAP_CFG1                     0x57U
#define LSM6DSOX_TAP_CFG2                     0x58U
#define LSM6DSOX_TAP_THS_6D                   0x59U
#define LSM6DSOX_INT_DUR2                     0x5AU
#define LSM6DSOX_WAKE_UP_THS                  0x5BU
#define LSM6DSOX_WAKE_UP_DUR                  0x5CU
#define LSM6DSOX_FREE_FALL                    0x5DU
#define LSM6DSOX_MD1_CFG                      0x5EU
#define LSM6DSOX_MD2_CFG                      0x5FU
#define LSM6DSOX_S4S_ST_CMD_CODE              0x60U
#define LSM6DSOX_S4S_DT_REG                   0x61U
#define LSM6DSOX_I3C_BUS_AVB                  0x62U
#define LSM6DSOX_INTERNAL_FREQ_FINE           0x63U
#define LSM6DSOX_UI_INT_OIS                   0x6F
#define LSM6DSOX_UI_CTRL1_OIS                 0x70U
#define LSM6DSOX_UI_CTRL2_OIS                 0x71U
#define LSM6DSOX_UI_CTRL3_OIS                 0x72U
#define LSM6DSOX_X_OFS_USR                    0x73U
#define LSM6DSOX_Y_OFS_USR                    0x74U
#define LSM6DSOX_Z_OFS_USR                    0x75U
#define LSM6DSOX_FIFO_DATA_OUT_TAG            0x78U
#define LSM6DSOX_FIFO_DATA_OUT_X_L            0x79
#define LSM6DSOX_FIFO_DATA_OUT_X_H            0x7A
#define LSM6DSOX_FIFO_DATA_OUT_Y_L            0x7B
#define LSM6DSOX_FIFO_DATA_OUT_Y_H            0x7C
#define LSM6DSOX_FIFO_DATA_OUT_Z_L            0x7D
#define LSM6DSOX_FIFO_DATA_OUT_Z_H            0x7E
#define LSM6DSOX_SPI2_WHO_AM_I                0x0F
#define LSM6DSOX_SPI2_STATUS_REG_OIS          0x1E
#define LSM6DSOX_SPI2_OUT_TEMP_L              0x20
#define LSM6DSOX_SPI2_OUT_TEMP_H              0x21
#define LSM6DSOX_SPI2_OUTX_L_G_OIS            0x22
#define LSM6DSOX_SPI2_OUTX_H_G_OIS            0x23
#define LSM6DSOX_SPI2_OUTY_L_G_OIS            0x24
#define LSM6DSOX_SPI2_OUTY_H_G_OIS            0x25
#define LSM6DSOX_SPI2_OUTZ_L_G_OIS            0x26
#define LSM6DSOX_SPI2_OUTZ_H_G_OIS            0x27
#define LSM6DSOX_SPI2_OUTX_L_A_OIS            0x28
#define LSM6DSOX_SPI2_OUTX_H_A_OIS            0x29
#define LSM6DSOX_SPI2_OUTY_L_A_OIS            0x2A
#define LSM6DSOX_SPI2_OUTY_H_A_OIS            0x2B
#define LSM6DSOX_SPI2_OUTZ_L_A_OIS            0x2C
#define LSM6DSOX_SPI2_OUTZ_H_A_OIS            0x2D
#define LSM6DSOX_SPI2_INT_OIS                 0x6F
#define LSM6DSOX_SPI2_CTRL1_OIS               0x70U
#define LSM6DSOX_SPI2_CTRL2_OIS               0x71U
#define LSM6DSOX_SPI2_CTRL3_OIS               0x72U
#define LSM6DSOX_PAGE_SEL                     0x02U
#define LSM6DSOX_EMB_FUNC_EN_A                0x04U
#define LSM6DSOX_EMB_FUNC_EN_B                0x05U
#define LSM6DSOX_PAGE_ADDRESS                 0x08U
#define LSM6DSOX_PAGE_VALUE                   0x09U
#define LSM6DSOX_EMB_FUNC_INT1                0x0AU
#define LSM6DSOX_FSM_INT1_A                   0x0BU
#define LSM6DSOX_FSM_INT1_B                   0x0CU
#define LSM6DSOX_MLC_INT1                     0x0DU
#define LSM6DSOX_EMB_FUNC_INT2                0x0EU
#define LSM6DSOX_FSM_INT2_A                   0x0FU
#define LSM6DSOX_FSM_INT2_B                   0x10U
#define LSM6DSOX_MLC_INT2                     0x11U
#define LSM6DSOX_EMB_FUNC_STATUS              0x12U
#define LSM6DSOX_FSM_STATUS_A                 0x13U
#define LSM6DSOX_FSM_STATUS_B                 0x14U
#define LSM6DSOX_MLC_STATUS                   0x15U
#define LSM6DSOX_PAGE_RW                      0x17U
#define LSM6DSOX_EMB_FUNC_FIFO_CFG             0x44U
#define LSM6DSOX_FSM_ENABLE_A                 0x46U
#define LSM6DSOX_FSM_ENABLE_B                 0x47U
#define LSM6DSOX_FSM_LONG_COUNTER_L           0x48U
#define LSM6DSOX_FSM_LONG_COUNTER_H           0x49U
#define LSM6DSOX_FSM_LONG_COUNTER_CLEAR       0x4AU
#define LSM6DSOX_FSM_OUTS1                    0x4CU
#define LSM6DSOX_FSM_OUTS2                    0x4DU
#define LSM6DSOX_FSM_OUTS3                    0x4EU
#define LSM6DSOX_FSM_OUTS4                    0x4FU
#define LSM6DSOX_FSM_OUTS5                    0x50U
#define LSM6DSOX_FSM_OUTS6                    0x51U
#define LSM6DSOX_FSM_OUTS7                    0x52U
#define LSM6DSOX_FSM_OUTS8                    0x53U
#define LSM6DSOX_FSM_OUTS9                    0x54U
#define LSM6DSOX_FSM_OUTS10                   0x55U
#define LSM6DSOX_FSM_OUTS11                   0x56U
#define LSM6DSOX_FSM_OUTS12                   0x57U
#define LSM6DSOX_FSM_OUTS13                   0x58U
#define LSM6DSOX_FSM_OUTS14                   0x59U
#define LSM6DSOX_FSM_OUTS15                   0x5AU
#define LSM6DSOX_FSM_OUTS16                   0x5BU
#define LSM6DSOX_EMB_FUNC_ODR_CFG_B           0x5FU
#define LSM6DSOX_EMB_FUNC_ODR_CFG_C           0x60U
#define LSM6DSOX_STEP_COUNTER_L               0x62U
#define LSM6DSOX_STEP_COUNTER_H               0x63U
#define LSM6DSOX_EMB_FUNC_SRC                 0x64U
#define LSM6DSOX_EMB_FUNC_INIT_A              0x66U
#define LSM6DSOX_EMB_FUNC_INIT_B              0x67U
#define LSM6DSOX_MLC0_SRC                     0x70U
#define LSM6DSOX_MLC1_SRC                     0x71U
#define LSM6DSOX_MLC2_SRC                     0x72U
#define LSM6DSOX_MLC3_SRC                     0x73U
#define LSM6DSOX_MLC4_SRC                     0x74U
#define LSM6DSOX_MLC5_SRC                     0x75U
#define LSM6DSOX_MLC6_SRC                     0x76U
#define LSM6DSOX_MLC7_SRC                     0x77U
#define LSM6DSOX_MAG_SENSITIVITY_L            0xBAU
#define LSM6DSOX_MAG_SENSITIVITY_H            0xBBU
#define LSM6DSOX_MAG_OFFX_L                   0xC0U
#define LSM6DSOX_MAG_OFFX_H                   0xC1U
#define LSM6DSOX_MAG_OFFY_L                   0xC2U
#define LSM6DSOX_MAG_OFFY_H                   0xC3U
#define LSM6DSOX_MAG_OFFZ_L                   0xC4U
#define LSM6DSOX_MAG_OFFZ_H                   0xC5U
#define LSM6DSOX_MAG_SI_XX_L                  0xC6U
#define LSM6DSOX_MAG_SI_XX_H                  0xC7U
#define LSM6DSOX_MAG_SI_XY_L                  0xC8U
#define LSM6DSOX_MAG_SI_XY_H                  0xC9U
#define LSM6DSOX_MAG_SI_XZ_L                  0xCAU
#define LSM6DSOX_MAG_SI_XZ_H                  0xCBU
#define LSM6DSOX_MAG_SI_YY_L                  0xCCU
#define LSM6DSOX_MAG_SI_YY_H                  0xCDU
#define LSM6DSOX_MAG_SI_YZ_L                  0xCEU
#define LSM6DSOX_MAG_SI_YZ_H                  0xCFU
#define LSM6DSOX_MAG_SI_ZZ_L                  0xD0U
#define LSM6DSOX_MAG_SI_ZZ_H                  0xD1U
#define LSM6DSOX_MAG_CFG_A                    0xD4U
#define LSM6DSOX_MAG_CFG_B                    0xD5U
#define LSM6DSOX_FSM_LC_TIMEOUT_L             0x17AU
#define LSM6DSOX_FSM_LC_TIMEOUT_H             0x17BU
#define LSM6DSOX_FSM_PROGRAMS                 0x17CU
#define LSM6DSOX_FSM_START_ADD_L              0x17EU
#define LSM6DSOX_FSM_START_ADD_H              0x17FU
#define LSM6DSOX_PEDO_CMD_REG                 0x183U
#define LSM6DSOX_PEDO_DEB_STEPS_CONF          0x184U
#define LSM6DSOX_PEDO_SC_DELTAT_L             0x1D0U
#define LSM6DSOX_PEDO_SC_DELTAT_H             0x1D1U
#define LSM6DSOX_MLC_MAG_SENSITIVITY_L        0x1E8U
#define LSM6DSOX_MLC_MAG_SENSITIVITY_H        0x1E9U
#define LSM6DSOX_SENSOR_HUB_1                 0x02U
#define LSM6DSOX_SENSOR_HUB_2                 0x03U
#define LSM6DSOX_SENSOR_HUB_3                 0x04U
#define LSM6DSOX_SENSOR_HUB_4                 0x05U
#define LSM6DSOX_SENSOR_HUB_5                 0x06U
#define LSM6DSOX_SENSOR_HUB_6                 0x07U
#define LSM6DSOX_SENSOR_HUB_7                 0x08U
#define LSM6DSOX_SENSOR_HUB_8                 0x09U
#define LSM6DSOX_SENSOR_HUB_9                 0x0AU
#define LSM6DSOX_SENSOR_HUB_10                0x0BU
#define LSM6DSOX_SENSOR_HUB_11                0x0CU
#define LSM6DSOX_SENSOR_HUB_12                0x0DU
#define LSM6DSOX_SENSOR_HUB_13                0x0EU
#define LSM6DSOX_SENSOR_HUB_14                0x0FU
#define LSM6DSOX_SENSOR_HUB_15                0x10U
#define LSM6DSOX_SENSOR_HUB_16                0x11U
#define LSM6DSOX_SENSOR_HUB_17                0x12U
#define LSM6DSOX_SENSOR_HUB_18                0x13U
#define LSM6DSOX_MASTER_CONFIG                0x14U
#define LSM6DSOX_SLV0_ADD                     0x15U
#define LSM6DSOX_SLV0_SUBADD                  0x16U
#define LSM6DSOX_SLV0_CONFIG                  0x17U
#define LSM6DSOX_SLV1_ADD                     0x18U
#define LSM6DSOX_SLV1_SUBADD                  0x19U
#define LSM6DSOX_SLV1_CONFIG                  0x1AU
#define LSM6DSOX_SLV2_ADD                     0x1BU
#define LSM6DSOX_SLV2_SUBADD                  0x1CU
#define LSM6DSOX_SLV2_CONFIG                  0x1DU
#define LSM6DSOX_SLV3_ADD                     0x1EU
#define LSM6DSOX_SLV3_SUBADD                  0x1FU
#define LSM6DSOX_SLV3_CONFIG                  0x20U
#define LSM6DSOX_DATAWRITE_SLV0               0x21U
#define LSM6DSOX_STATUS_MASTER                0x22U
#define LSM6DSOX_START_FSM_ADD                0x0400U


#endif /* MAIN_COMPONENTS_LSM6DSOX_LSM_DEFINES_H_ */
